#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

sketchybar --bar \
  position=bottom \
  height=50 \
  color=$ISLAND_BG \
  border_width=0 \
  shadow=on \
  sticky=on \
  margin=10 \
  y_offset=4 \
  corner_radius=9 \
  blur_radius=30 \
  padding_left=18 \
  padding_right=18

sketchybar --default \
  icon.font="JetBrainsMono Nerd Font Mono:Bold:14.0" \
  label.font="JetBrainsMono Nerd Font Mono:Medium:13.0" \
  icon.color=$ICN_FG \
  label.color=$SD_FG \
  icon.shadow.drawing=on \
  icon.shadow.color=0x60000000 \
  icon.shadow.distance=1 \
  label.shadow.drawing=on \
  label.shadow.color=0x60000000 \
  label.shadow.distance=1 \
  background.drawing=off \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=4 \
  label.padding_right=4 \
  icon.padding_left=8 \
  icon.padding_right=4

sketchybar --add event aerospace_workspace_change

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/teams.sh"
source "$ITEM_DIR/spotify.sh"
source "$ITEM_DIR/date.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --update
